function soln = cir_zero_comp_solve(r,c0,u0,v0)
%CIR_ZERO_COMP_SOLVE
%   Solves the scalar equation for theta
%
%   0 = c0 + r*u0*cos(theta) + r*v0*sin(theta)
%
%
%    SOLN = CIR_ZERO_COMP_SOLVE(C0,R,U0,V0)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Aug-2020 23:21:00

t2 = r.*u0;
t3 = c0.^2;
t4 = r.^2;
t5 = u0.^2;
t6 = v0.^2;
t7 = r.*v0.*1i;
t8 = t2.^2;
t9 = t4.*t6;
t10 = -t7;
t11 = -t8;
t12 = -t9;
t13 = t2+t10;
t14 = 1.0./t13;
t15 = t3+t11+t12;
t16 = sqrt(t15);
soln = [log(-t14.*(c0+t16)).*-1i;log(-t14.*(c0-t16)).*-1i];
