function pts = plane_circ_int(r,xn,xp,yn,yp,zn,zp)
%PLANE_CIRC_INT
%    PTS = PLANE_CIRC_INT(R,XN,XP,YN,YP,ZN,ZP)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Aug-2020 00:13:54

t2 = xn.*xp;
t3 = yn.*yp;
t4 = zn.*zp;
t5 = r.^2;
t6 = xn.^2;
t7 = xp.^2;
t8 = yn.^2;
t9 = yp.^2;
t10 = zn.^2;
t11 = zp.^2;
t14 = 1.0./xn;
t12 = t2.*yn;
t13 = t4.*yn;
t15 = t3.*yn;
t16 = t2.*t3.*2.0;
t17 = t2.*t4.*2.0;
t18 = t3.*t4.*2.0;
t19 = t5.*t6;
t20 = t5.*t8;
t21 = t2.^2;
t22 = t6+t8;
t23 = t3.^2;
t24 = t4.^2;
t31 = t2+t3+t4;
t25 = -t16;
t26 = -t17;
t27 = -t18;
t28 = -t21;
t29 = -t23;
t30 = -t24;
t32 = 1.0./t22;
t33 = t14.*t31;
t34 = t19+t20+t25+t26+t27+t28+t29+t30;
t35 = sqrt(t34);
t36 = t35.*xn;
t37 = -t36;
t38 = t12+t13+t15+t36;
t39 = t12+t13+t15+t37;
pts = reshape([t33-t14.*t32.*t38.*yn,t32.*t38,t33-t14.*t32.*t39.*yn,t32.*t39],[2,2]);
